-- --------------------------------------------------------
-- Uninstall sql
-- --------------------------------------------------------

-- DROP TABLE IF EXISTS `#__survey_force_config`;
-- DROP TABLE IF EXISTS `#__survey_force_user_chain`;
-- DROP TABLE IF EXISTS `#__survey_force_previews`;
-- DROP TABLE IF EXISTS `#__survey_force_templates`;
-- DROP TABLE IF EXISTS `#__survey_force_cats`;
-- DROP TABLE IF EXISTS `#__survey_force_emails`;
-- DROP TABLE IF EXISTS `#__survey_force_fields`;
-- DROP TABLE IF EXISTS `#__survey_force_invitations`;
-- DROP TABLE IF EXISTS `#__survey_force_iscales`;
-- DROP TABLE IF EXISTS `#__survey_force_iscales_fields`;
-- DROP TABLE IF EXISTS `#__survey_force_listusers`;
-- DROP TABLE IF EXISTS `#__survey_force_qtypes`;
-- DROP TABLE IF EXISTS `#__survey_force_quests`;
-- DROP TABLE IF EXISTS `#__survey_force_rules`;
-- DROP TABLE IF EXISTS `#__survey_force_rules`;
-- DROP TABLE IF EXISTS `#__survey_force_scales`;
-- DROP TABLE IF EXISTS `#__survey_force_survs`;
-- DROP TABLE IF EXISTS `#__survey_force_user_ans_txt`;
-- DROP TABLE IF EXISTS `#__survey_force_user_answers`;
-- DROP TABLE IF EXISTS `#__survey_force_user_answers_imp`;
-- DROP TABLE IF EXISTS `#__survey_force_user_starts`;
-- DROP TABLE IF EXISTS `#__survey_force_users`;
-- DROP TABLE IF EXISTS `#__survey_force_qsections`;
-- DROP TABLE IF EXISTS `#__survey_force_def_answers`;
-- DROP TABLE IF EXISTS `#__survey_force_authors`;
-- DROP TABLE IF EXISTS `#__survey_force_quest_show`;
-- DROP TABLE IF EXISTS `#__survey_force_dashboard_items`;